export const numberData = [
    { japanese_character: 'ゼロ', romaji_character: '0', alphabet_audio: 'D:/alphabet/number/audio/0', alphabet_image: 'D:/alphabet/number/image/0' },
    { japanese_character: 'いち', romaji_character: '1', alphabet_audio: 'D:/alphabet/number/audio/1', alphabet_image: 'D:/alphabet/number/image/1' },
    { japanese_character: 'に', romaji_character: '2', alphabet_audio: 'D:/alphabet/number/audio/2', alphabet_image: 'D:/alphabet/number/image/2' },
    { japanese_character: 'さん', romaji_character: '3', alphabet_audio: 'D:/alphabet/number/audio/3', alphabet_image: 'D:/alphabet/number/image/3' },
    { japanese_character: 'し', romaji_character: '4', alphabet_audio: 'D:/alphabet/number/audio/4', alphabet_image: 'D:/alphabet/number/image/4' },
    { japanese_character: 'ご', romaji_character: '5', alphabet_audio: 'D:/alphabet/number/audio/5', alphabet_image: 'D:/alphabet/number/image/5' },
    { japanese_character: 'ろく', romaji_character: '6', alphabet_audio: 'D:/alphabet/number/audio/6', alphabet_image: 'D:/alphabet/number/image/6' },
    { japanese_character: 'しち', romaji_character: '7', alphabet_audio: 'D:/alphabet/number/audio/7', alphabet_image: 'D:/alphabet/number/image/7' },
    { japanese_character: 'はち', romaji_character: '8', alphabet_audio: 'D:/alphabet/number/audio/8', alphabet_image: 'D:/alphabet/number/image/8' },
    { japanese_character: 'きゅう', romaji_character: '9', alphabet_audio: 'D:/alphabet/number/audio/9', alphabet_image: 'D:/alphabet/number/image/9' },
    { japanese_character: 'じゅう', romaji_character: '10', alphabet_audio: 'D:/alphabet/number/audio/10', alphabet_image: 'D:/alphabet/number/image/10' },
    { japanese_character: 'じゅうご', romaji_character: '15', alphabet_audio: 'D:/alphabet/number/audio/15', alphabet_image: 'D:/alphabet/number/image/15' },
    { japanese_character: 'にじゅう', romaji_character: '20', alphabet_audio: 'D:/alphabet/number/audio/20', alphabet_image: 'D:/alphabet/number/image/20' },
    { japanese_character: 'ごじゅう', romaji_character: '50', alphabet_audio: 'D:/alphabet/number/audio/50', alphabet_image: 'D:/alphabet/number/image/50' },
    { japanese_character: 'ひゃく', romaji_character: '100', alphabet_audio: 'D:/alphabet/number/audio/100', alphabet_image: 'D:/alphabet/number/image/100' },
    { japanese_character: 'にひゃく', romaji_character: '200', alphabet_audio: 'D:/alphabet/number/audio/100', alphabet_image: 'D:/alphabet/number/image/200' },
    { japanese_character: 'さんびゃく', romaji_character: '300', alphabet_audio: 'D:/alphabet/number/audio/100', alphabet_image: 'D:/alphabet/number/image/300' },
    { japanese_character: 'ろっぴゃく', romaji_character: '600', alphabet_audio: 'D:/alphabet/number/audio/100', alphabet_image: 'D:/alphabet/number/image/600' },
    { japanese_character: 'はっぴゃく', romaji_character: '800', alphabet_audio: 'D:/alphabet/number/audio/100', alphabet_image: 'D:/alphabet/number/image/800' },
    { japanese_character: 'せん', romaji_character: '1000', alphabet_audio: 'D:/alphabet/number/audio/1000', alphabet_image: 'D:/alphabet/number/image/1000' },
    { japanese_character: 'にせん', romaji_character: '2000', alphabet_audio: 'D:/alphabet/number/audio/1000', alphabet_image: 'D:/alphabet/number/image/2000' },
    { japanese_character: 'さんぜん', romaji_character: '3000', alphabet_audio: 'D:/alphabet/number/audio/1000', alphabet_image: 'D:/alphabet/number/image/3000' },
    { japanese_character: 'ごせん', romaji_character: '5000', alphabet_audio: 'D:/alphabet/number/audio/1000', alphabet_image: 'D:/alphabet/number/image/5000' },
    { japanese_character: 'はっせん', romaji_character: '8000', alphabet_audio: 'D:/alphabet/number/audio/1000', alphabet_image: 'D:/alphabet/number/image/8000' },
    { japanese_character: 'まん', romaji_character: '10000', alphabet_audio: 'D:/alphabet/number/audio/10000', alphabet_image: 'D:/alphabet/number/image/10000' },
  ];
  