export const dakutenKatakana = [
  { japanese_character: 'ガ', romaji_character: 'ga', alphabet_audio: 'D:/alphabet/katakana/audio/ga', alphabet_image: 'D:/alphabet/katakana/image/ga' },
  { japanese_character: 'ギ', romaji_character: 'gi', alphabet_audio: 'D:/alphabet/katakana/audio/gi', alphabet_image: 'D:/alphabet/katakana/image/gi' },
  { japanese_character: 'グ', romaji_character: 'gu', alphabet_audio: 'D:/alphabet/katakana/audio/gu', alphabet_image: 'D:/alphabet/katakana/image/gu' },
  { japanese_character: 'ゲ', romaji_character: 'ge', alphabet_audio: 'D:/alphabet/katakana/audio/ge', alphabet_image: 'D:/alphabet/katakana/image/ge' },
  { japanese_character: 'ゴ', romaji_character: 'go', alphabet_audio: 'D:/alphabet/katakana/audio/go', alphabet_image: 'D:/alphabet/katakana/image/go' },
  { japanese_character: 'ザ', romaji_character: 'za', alphabet_audio: 'D:/alphabet/katakana/audio/za', alphabet_image: 'D:/alphabet/katakana/image/za' },
  { japanese_character: 'ジ', romaji_character: 'ji', alphabet_audio: 'D:/alphabet/katakana/audio/ji', alphabet_image: 'D:/alphabet/katakana/image/ji' },
  { japanese_character: 'ズ', romaji_character: 'zu', alphabet_audio: 'D:/alphabet/katakana/audio/zu', alphabet_image: 'D:/alphabet/katakana/image/zu' },
  { japanese_character: 'ゼ', romaji_character: 'ze', alphabet_audio: 'D:/alphabet/katakana/audio/ze', alphabet_image: 'D:/alphabet/katakana/image/ze' },
  { japanese_character: 'ゾ', romaji_character: 'zo', alphabet_audio: 'D:/alphabet/katakana/audio/zo', alphabet_image: 'D:/alphabet/katakana/image/zo' },
  { japanese_character: 'ダ', romaji_character: 'da', alphabet_audio: 'D:/alphabet/katakana/audio/da', alphabet_image: 'D:/alphabet/katakana/image/da' },
  { japanese_character: 'ヂ', romaji_character: 'ji', alphabet_audio: 'D:/alphabet/katakana/audio/ji', alphabet_image: 'D:/alphabet/katakana/image/ji' },
  { japanese_character: 'ヅ', romaji_character: 'zu', alphabet_audio: 'D:/alphabet/katakana/audio/zu', alphabet_image: 'D:/alphabet/katakana/image/zu' },
  { japanese_character: 'デ', romaji_character: 'de', alphabet_audio: 'D:/alphabet/katakana/audio/de', alphabet_image: 'D:/alphabet/katakana/image/de' },
  { japanese_character: 'ド', romaji_character: 'do', alphabet_audio: 'D:/alphabet/katakana/audio/do', alphabet_image: 'D:/alphabet/katakana/image/do' },
  { japanese_character: 'バ', romaji_character: 'ba', alphabet_audio: 'D:/alphabet/katakana/audio/ba', alphabet_image: 'D:/alphabet/katakana/image/ba' },
  { japanese_character: 'ビ', romaji_character: 'bi', alphabet_audio: 'D:/alphabet/katakana/audio/bi', alphabet_image: 'D:/alphabet/katakana/image/bi' },
  { japanese_character: 'ブ', romaji_character: 'bu', alphabet_audio: 'D:/alphabet/katakana/audio/bu', alphabet_image: 'D:/alphabet/katakana/image/bu' },
  { japanese_character: 'ベ', romaji_character: 'be', alphabet_audio: 'D:/alphabet/katakana/audio/be', alphabet_image: 'D:/alphabet/katakana/image/be' },
  { japanese_character: 'ボ', romaji_character: 'bo', alphabet_audio: 'D:/alphabet/katakana/audio/bo', alphabet_image: 'D:/alphabet/katakana/image/bo' },
  { japanese_character: 'パ', romaji_character: 'pa', alphabet_audio: 'D:/alphabet/katakana/audio/pa', alphabet_image: 'D:/alphabet/katakana/image/pa' },
  { japanese_character: 'ピ', romaji_character: 'pi', alphabet_audio: 'D:/alphabet/katakana/audio/pi', alphabet_image: 'D:/alphabet/katakana/image/pi' },
  { japanese_character: 'プ', romaji_character: 'pu', alphabet_audio: 'D:/alphabet/katakana/audio/pu', alphabet_image: 'D:/alphabet/katakana/image/pu' },
  { japanese_character: 'ペ', romaji_character: 'pe', alphabet_audio: 'D:/alphabet/katakana/audio/pe', alphabet_image: 'D:/alphabet/katakana/image/pe' },
  { japanese_character: 'ポ', romaji_character: 'po', alphabet_audio: 'D:/alphabet/katakana/audio/po', alphabet_image: 'D:/alphabet/katakana/image/po' },
];
