export const katakana = [
  { japanese_character: 'ア', romaji_character: 'a', alphabet_audio: 'D:/alphabet/katakana/audio/a', alphabet_image: 'D:/alphabet/katakana/image/a' },
  { japanese_character: 'イ', romaji_character: 'i', alphabet_audio: 'D:/alphabet/katakana/audio/i', alphabet_image: 'D:/alphabet/katakana/image/i' },
  { japanese_character: 'ウ', romaji_character: 'u', alphabet_audio: 'D:/alphabet/katakana/audio/u', alphabet_image: 'D:/alphabet/katakana/image/u' },
  { japanese_character: 'エ', romaji_character: 'e', alphabet_audio: 'D:/alphabet/katakana/audio/e', alphabet_image: 'D:/alphabet/katakana/image/e' },
  { japanese_character: 'オ', romaji_character: 'o', alphabet_audio: 'D:/alphabet/katakana/audio/o', alphabet_image: 'D:/alphabet/katakana/image/o' },
  { japanese_character: 'カ', romaji_character: 'ka', alphabet_audio: 'D:/alphabet/katakana/audio/ka', alphabet_image: 'D:/alphabet/katakana/image/ka' },
  { japanese_character: 'キ', romaji_character: 'ki', alphabet_audio: 'D:/alphabet/katakana/audio/ki', alphabet_image: 'D:/alphabet/katakana/image/ki' },
  { japanese_character: 'ク', romaji_character: 'ku', alphabet_audio: 'D:/alphabet/katakana/audio/ku', alphabet_image: 'D:/alphabet/katakana/image/ku' },
  { japanese_character: 'ケ', romaji_character: 'ke', alphabet_audio: 'D:/alphabet/katakana/audio/ke', alphabet_image: 'D:/alphabet/katakana/image/ke' },
  { japanese_character: 'コ', romaji_character: 'ko', alphabet_audio: 'D:/alphabet/katakana/audio/ko', alphabet_image: 'D:/alphabet/katakana/image/ko' },
  { japanese_character: 'サ', romaji_character: 'sa', alphabet_audio: 'D:/alphabet/katakana/audio/sa', alphabet_image: 'D:/alphabet/katakana/image/sa' },
  { japanese_character: 'シ', romaji_character: 'shi', alphabet_audio: 'D:/alphabet/katakana/audio/shi', alphabet_image: 'D:/alphabet/katakana/image/shi' },
  { japanese_character: 'ス', romaji_character: 'su', alphabet_audio: 'D:/alphabet/katakana/audio/su', alphabet_image: 'D:/alphabet/katakana/image/su' },
  { japanese_character: 'セ', romaji_character: 'se', alphabet_audio: 'D:/alphabet/katakana/audio/se', alphabet_image: 'D:/alphabet/katakana/image/se' },
  { japanese_character: 'ソ', romaji_character: 'so', alphabet_audio: 'D:/alphabet/katakana/audio/so', alphabet_image: 'D:/alphabet/katakana/image/so' },
  { japanese_character: 'タ', romaji_character: 'ta', alphabet_audio: 'D:/alphabet/katakana/audio/ta', alphabet_image: 'D:/alphabet/katakana/image/ta' },
  { japanese_character: 'チ', romaji_character: 'chi', alphabet_audio: 'D:/alphabet/katakana/audio/chi', alphabet_image: 'D:/alphabet/katakana/image/chi' },
  { japanese_character: 'ツ', romaji_character: 'tsu', alphabet_audio: 'D:/alphabet/katakana/audio/tsu', alphabet_image: 'D:/alphabet/katakana/image/tsu' },
  { japanese_character: 'テ', romaji_character: 'te', alphabet_audio: 'D:/alphabet/katakana/audio/te', alphabet_image: 'D:/alphabet/katakana/image/te' },
  { japanese_character: 'ト', romaji_character: 'to', alphabet_audio: 'D:/alphabet/katakana/audio/to', alphabet_image: 'D:/alphabet/katakana/image/to' },
  { japanese_character: 'ナ', romaji_character: 'na', alphabet_audio: 'D:/alphabet/katakana/audio/na', alphabet_image: 'D:/alphabet/katakana/image/na' },
  { japanese_character: 'ニ', romaji_character: 'ni', alphabet_audio: 'D:/alphabet/katakana/audio/ni', alphabet_image: 'D:/alphabet/katakana/image/ni' },
  { japanese_character: 'ヌ', romaji_character: 'nu', alphabet_audio: 'D:/alphabet/katakana/audio/nu', alphabet_image: 'D:/alphabet/katakana/image/nu' },
  { japanese_character: 'ネ', romaji_character: 'ne', alphabet_audio: 'D:/alphabet/katakana/audio/ne', alphabet_image: 'D:/alphabet/katakana/image/ne' },
  { japanese_character: 'ノ', romaji_character: 'no', alphabet_audio: 'D:/alphabet/katakana/audio/no', alphabet_image: 'D:/alphabet/katakana/image/no' },
  { japanese_character: 'ハ', romaji_character: 'ha', alphabet_audio: 'D:/alphabet/katakana/audio/ha', alphabet_image: 'D:/alphabet/katakana/image/ha' },
  { japanese_character: 'ヒ', romaji_character: 'hi', alphabet_audio: 'D:/alphabet/katakana/audio/hi', alphabet_image: 'D:/alphabet/katakana/image/hi' },
  { japanese_character: 'フ', romaji_character: 'fu', alphabet_audio: 'D:/alphabet/katakana/audio/fu', alphabet_image: 'D:/alphabet/katakana/image/fu' },
  { japanese_character: 'ヘ', romaji_character: 'he', alphabet_audio: 'D:/alphabet/katakana/audio/he', alphabet_image: 'D:/alphabet/katakana/image/he' },
  { japanese_character: 'ホ', romaji_character: 'ho', alphabet_audio: 'D:/alphabet/katakana/audio/ho', alphabet_image: 'D:/alphabet/katakana/image/ho' },
  { japanese_character: 'マ', romaji_character: 'ma', alphabet_audio: 'D:/alphabet/katakana/audio/ma', alphabet_image: 'D:/alphabet/katakana/image/ma' },
  { japanese_character: 'ミ', romaji_character: 'mi', alphabet_audio: 'D:/alphabet/katakana/audio/mi', alphabet_image: 'D:/alphabet/katakana/image/mi' },
  { japanese_character: 'ム', romaji_character: 'mu', alphabet_audio: 'D:/alphabet/katakana/audio/mu', alphabet_image: 'D:/alphabet/katakana/image/mu' },
  { japanese_character: 'メ', romaji_character: 'me', alphabet_audio: 'D:/alphabet/katakana/audio/me', alphabet_image: 'D:/alphabet/katakana/image/me' },
  { japanese_character: 'モ', romaji_character: 'mo', alphabet_audio: 'D:/alphabet/katakana/audio/mo', alphabet_image: 'D:/alphabet/katakana/image/mo' },
  { japanese_character: 'ヤ', romaji_character: 'ya', alphabet_audio: 'D:/alphabet/katakana/audio/ya', alphabet_image: 'D:/alphabet/katakana/image/ya' },
  { japanese_character: '', romaji_character: '', alphabet_audio: '', alphabet_image: '' }, // Ô trống sau "ya"
  { japanese_character: 'ユ', romaji_character: 'yu', alphabet_audio: 'D:/alphabet/katakana/audio/yu', alphabet_image: 'D:/alphabet/katakana/image/yu' },
  { japanese_character: '', romaji_character: '', alphabet_audio: '', alphabet_image: '' }, // Ô trống sau "yu"
  { japanese_character: 'ヨ', romaji_character: 'yo', alphabet_audio: 'D:/alphabet/katakana/audio/yo', alphabet_image: 'D:/alphabet/katakana/image/yo' },
  { japanese_character: 'ラ', romaji_character: 'ra', alphabet_audio: 'D:/alphabet/katakana/audio/ra', alphabet_image: 'D:/alphabet/katakana/image/ra' },
  { japanese_character: 'リ', romaji_character: 'ri', alphabet_audio: 'D:/alphabet/katakana/audio/ri', alphabet_image: 'D:/alphabet/katakana/image/ri' },
  { japanese_character: 'ル', romaji_character: 'ru', alphabet_audio: 'D:/alphabet/katakana/audio/ru', alphabet_image: 'D:/alphabet/katakana/image/ru' },
  { japanese_character: 'レ', romaji_character: 're', alphabet_audio: 'D:/alphabet/katakana/audio/re', alphabet_image: 'D:/alphabet/katakana/image/re' },
  { japanese_character: 'ロ', romaji_character: 'ro', alphabet_audio: 'D:/alphabet/katakana/audio/ro', alphabet_image: 'D:/alphabet/katakana/image/ro' },
  { japanese_character: 'ワ', romaji_character: 'wa', alphabet_audio: 'D:/alphabet/katakana/audio/wa', alphabet_image: 'D:/alphabet/katakana/image/wa' },
  { japanese_character: '', romaji_character: '', alphabet_audio: '', alphabet_image: '' }, // Ô trống sau "wa"
  { japanese_character: 'ヲ', romaji_character: 'wo', alphabet_audio: 'D:/alphabet/katakana/audio/wo', alphabet_image: 'D:/alphabet/katakana/image/wo' },
  { japanese_character: '', romaji_character: '', alphabet_audio: '', alphabet_image: '' }, // Ô trống sau "wo"
  { japanese_character: 'ン', romaji_character: 'n', alphabet_audio: 'D:/alphabet/katakana/audio/n', alphabet_image: 'D:/alphabet/katakana/image/n' },
];
