export const dakutenHiragana = [
  { japanese_character: 'が', romaji_character: 'ga', alphabet_audio: 'D:/alphabet/hiragana/audio/ga', alphabet_image: 'D:/alphabet/hiragana/image/ga' },
  { japanese_character: 'ぎ', romaji_character: 'gi', alphabet_audio: 'D:/alphabet/hiragana/audio/gi', alphabet_image: 'D:/alphabet/hiragana/image/gi' },
  { japanese_character: 'ぐ', romaji_character: 'gu', alphabet_audio: 'D:/alphabet/hiragana/audio/gu', alphabet_image: 'D:/alphabet/hiragana/image/gu' },
  { japanese_character: 'げ', romaji_character: 'ge', alphabet_audio: 'D:/alphabet/hiragana/audio/ge', alphabet_image: 'D:/alphabet/hiragana/image/ge' },
  { japanese_character: 'ご', romaji_character: 'go', alphabet_audio: 'D:/alphabet/hiragana/audio/go', alphabet_image: 'D:/alphabet/hiragana/image/go' },
  { japanese_character: 'ざ', romaji_character: 'za', alphabet_audio: 'D:/alphabet/hiragana/audio/za', alphabet_image: 'D:/alphabet/hiragana/image/za' },
  { japanese_character: 'じ', romaji_character: 'ji', alphabet_audio: 'D:/alphabet/hiragana/audio/ji', alphabet_image: 'D:/alphabet/hiragana/image/ji' },
  { japanese_character: 'ず', romaji_character: 'zu', alphabet_audio: 'D:/alphabet/hiragana/audio/zu', alphabet_image: 'D:/alphabet/hiragana/image/zu' },
  { japanese_character: 'ぜ', romaji_character: 'ze', alphabet_audio: 'D:/alphabet/hiragana/audio/ze', alphabet_image: 'D:/alphabet/hiragana/image/ze' },
  { japanese_character: 'ぞ', romaji_character: 'zo', alphabet_audio: 'D:/alphabet/hiragana/audio/zo', alphabet_image: 'D:/alphabet/hiragana/image/zo' },
  { japanese_character: 'だ', romaji_character: 'da', alphabet_audio: 'D:/alphabet/hiragana/audio/da', alphabet_image: 'D:/alphabet/hiragana/image/da' },
  { japanese_character: 'ぢ', romaji_character: 'ji', alphabet_audio: 'D:/alphabet/hiragana/audio/ji', alphabet_image: 'D:/alphabet/hiragana/image/ji' },
  { japanese_character: 'づ', romaji_character: 'zu', alphabet_audio: 'D:/alphabet/hiragana/audio/zu', alphabet_image: 'D:/alphabet/hiragana/image/zu' },
  { japanese_character: 'で', romaji_character: 'de', alphabet_audio: 'D:/alphabet/hiragana/audio/de', alphabet_image: 'D:/alphabet/hiragana/image/de' },
  { japanese_character: 'ど', romaji_character: 'do', alphabet_audio: 'D:/alphabet/hiragana/audio/do', alphabet_image: 'D:/alphabet/hiragana/image/do' },
  { japanese_character: 'ば', romaji_character: 'ba', alphabet_audio: 'D:/alphabet/hiragana/audio/ba', alphabet_image: 'D:/alphabet/hiragana/image/ba' },
  { japanese_character: 'び', romaji_character: 'bi', alphabet_audio: 'D:/alphabet/hiragana/audio/bi', alphabet_image: 'D:/alphabet/hiragana/image/bi' },
  { japanese_character: 'ぶ', romaji_character: 'bu', alphabet_audio: 'D:/alphabet/hiragana/audio/bu', alphabet_image: 'D:/alphabet/hiragana/image/bu' },
  { japanese_character: 'べ', romaji_character: 'be', alphabet_audio: 'D:/alphabet/hiragana/audio/be', alphabet_image: 'D:/alphabet/hiragana/image/be' },
  { japanese_character: 'ぼ', romaji_character: 'bo', alphabet_audio: 'D:/alphabet/hiragana/audio/bo', alphabet_image: 'D:/alphabet/hiragana/image/bo' },
  { japanese_character: 'ぱ', romaji_character: 'pa', alphabet_audio: 'D:/alphabet/hiragana/audio/pa', alphabet_image: 'D:/alphabet/hiragana/image/pa' },
  { japanese_character: 'ぴ', romaji_character: 'pi', alphabet_audio: 'D:/alphabet/hiragana/audio/pi', alphabet_image: 'D:/alphabet/hiragana/image/pi' },
  { japanese_character: 'ぷ', romaji_character: 'pu', alphabet_audio: 'D:/alphabet/hiragana/audio/pu', alphabet_image: 'D:/alphabet/hiragana/image/pu' },
  { japanese_character: 'ぺ', romaji_character: 'pe', alphabet_audio: 'D:/alphabet/hiragana/audio/pe', alphabet_image: 'D:/alphabet/hiragana/image/pe' },
  { japanese_character: 'ぽ', romaji_character: 'po', alphabet_audio: 'D:/alphabet/hiragana/audio/po', alphabet_image: 'D:/alphabet/hiragana/image/po' },
];
