export const hiragana = [
  { japanese_character: 'あ', romaji_character: 'a', alphabet_audio: '/alphabet/hiragana/audio/a.mp3', alphabet_image: '/alphabet/hiragana/image/a.gif'},
  { japanese_character: 'い', romaji_character: 'i', alphabet_audio: '/alphabet/hiragana/audio/i.mp3', alphabet_image: '/alphabet/hiragana/image/i.gif'},
  { japanese_character: 'う', romaji_character: 'u', alphabet_audio: '/alphabet/hiragana/audio/u.mp3', alphabet_image: '/alphabet/hiragana/image/u.gif'},
  { japanese_character: 'え', romaji_character: 'e', alphabet_audio: '/alphabet/hiragana/audio/e.mp3', alphabet_image: '/alphabet/hiragana/image/e.gif'},
  { japanese_character: 'お', romaji_character: 'o', alphabet_audio: '/alphabet/hiragana/audio/o.mp3', alphabet_image: '/alphabet/hiragana/image/o.gif'},
  { japanese_character: 'か', romaji_character: 'ka', alphabet_audio: 'D:/alphabet/hiragana/audio/ka', alphabet_image: 'D:/alphabet/hiragana/image/ka'},
  { japanese_character: 'き', romaji_character: 'ki', alphabet_audio: 'D:/alphabet/hiragana/audio/ki', alphabet_image: 'D:/alphabet/hiragana/image/ki'},
  { japanese_character: 'く', romaji_character: 'ku', alphabet_audio: 'D:/alphabet/hiragana/audio/ku', alphabet_image: 'D:/alphabet/hiragana/image/ku'},
  { japanese_character: 'け', romaji_character: 'ke', alphabet_audio: 'D:/alphabet/hiragana/audio/ke', alphabet_image: 'D:/alphabet/hiragana/image/ke'},
  { japanese_character: 'こ', romaji_character: 'ko', alphabet_audio: 'D:/alphabet/hiragana/audio/ko', alphabet_image: 'D:/alphabet/hiragana/image/ko'},
  { japanese_character: 'さ', romaji_character: 'sa', alphabet_audio: 'D:/alphabet/hiragana/audio/sa', alphabet_image: 'D:/alphabet/hiragana/image/sa'},
  { japanese_character: 'し', romaji_character: 'shi', alphabet_audio: 'D:/alphabet/hiragana/audio/shi', alphabet_image: 'D:/alphabet/hiragana/image/shi'},
  { japanese_character: 'す', romaji_character: 'su', alphabet_audio: 'D:/alphabet/hiragana/audio/su', alphabet_image: 'D:/alphabet/hiragana/image/su'},
  { japanese_character: 'せ', romaji_character: 'se', alphabet_audio: 'D:/alphabet/hiragana/audio/se', alphabet_image: 'D:/alphabet/hiragana/image/se'},
  { japanese_character: 'そ', romaji_character: 'so', alphabet_audio: 'D:/alphabet/hiragana/audio/so', alphabet_image: 'D:/alphabet/hiragana/image/so'},
  { japanese_character: 'た', romaji_character: 'ta', alphabet_audio: 'D:/alphabet/hiragana/audio/ta', alphabet_image: 'D:/alphabet/hiragana/image/ta'},
  { japanese_character: 'ち', romaji_character: 'chi', alphabet_audio: 'D:/alphabet/hiragana/audio/chi', alphabet_image: 'D:/alphabet/hiragana/image/chi'},
  { japanese_character: 'つ', romaji_character: 'tsu', alphabet_audio: 'D:/alphabet/hiragana/audio/tsu', alphabet_image: 'D:/alphabet/hiragana/image/tsu'},
  { japanese_character: 'て', romaji_character: 'te', alphabet_audio: 'D:/alphabet/hiragana/audio/te', alphabet_image: 'D:/alphabet/hiragana/image/te'},
  { japanese_character: 'と', romaji_character: 'to', alphabet_audio: 'D:/alphabet/hiragana/audio/to', alphabet_image: 'D:/alphabet/hiragana/image/to'},
  { japanese_character: 'な', romaji_character: 'na', alphabet_audio: 'D:/alphabet/hiragana/audio/na', alphabet_image: 'D:/alphabet/hiragana/image/na'},
  { japanese_character: 'に', romaji_character: 'ni', alphabet_audio: 'D:/alphabet/hiragana/audio/ni', alphabet_image: 'D:/alphabet/hiragana/image/ni'},
  { japanese_character: 'ぬ', romaji_character: 'nu', alphabet_audio: 'D:/alphabet/hiragana/audio/nu', alphabet_image: 'D:/alphabet/hiragana/image/nu'},
  { japanese_character: 'ね', romaji_character: 'ne', alphabet_audio: 'D:/alphabet/hiragana/audio/ne', alphabet_image: 'D:/alphabet/hiragana/image/ne'},
  { japanese_character: 'の', romaji_character: 'no', alphabet_audio: 'D:/alphabet/hiragana/audio/no', alphabet_image: 'D:/alphabet/hiragana/image/no'},
  { japanese_character: 'は', romaji_character: 'ha', alphabet_audio: 'D:/alphabet/hiragana/audio/ha', alphabet_image: 'D:/alphabet/hiragana/image/ha'},
  { japanese_character: 'ひ', romaji_character: 'hi', alphabet_audio: 'D:/alphabet/hiragana/audio/hi', alphabet_image: 'D:/alphabet/hiragana/image/hi'},
  { japanese_character: 'ふ', romaji_character: 'fu', alphabet_audio: 'D:/alphabet/hiragana/audio/fu', alphabet_image: 'D:/alphabet/hiragana/image/fu'},
  { japanese_character: 'へ', romaji_character: 'he', alphabet_audio: 'D:/alphabet/hiragana/audio/he', alphabet_image: 'D:/alphabet/hiragana/image/he'},
  { japanese_character: 'ほ', romaji_character: 'ho', alphabet_audio: 'D:/alphabet/hiragana/audio/ho', alphabet_image: 'D:/alphabet/hiragana/image/ho'},
  { japanese_character: 'ま', romaji_character: 'ma', alphabet_audio: 'D:/alphabet/hiragana/audio/ma', alphabet_image: 'D:/alphabet/hiragana/image/ma'},
  { japanese_character: 'み', romaji_character: 'mi', alphabet_audio: 'D:/alphabet/hiragana/audio/mi', alphabet_image: 'D:/alphabet/hiragana/image/mi'},
  { japanese_character: 'む', romaji_character: 'mu', alphabet_audio: 'D:/alphabet/hiragana/audio/mu', alphabet_image: 'D:/alphabet/hiragana/image/mu'},
  { japanese_character: 'め', romaji_character: 'me', alphabet_audio: 'D:/alphabet/hiragana/audio/me', alphabet_image: 'D:/alphabet/hiragana/image/me'},
  { japanese_character: 'も', romaji_character: 'mo', alphabet_audio: 'D:/alphabet/hiragana/audio/mo', alphabet_image: 'D:/alphabet/hiragana/image/mo'},
  { japanese_character: 'や', romaji_character: 'ya', alphabet_audio: 'D:/alphabet/hiragana/audio/ya', alphabet_image: 'D:/alphabet/hiragana/image/ya'},
  { japanese_character: '', romaji_character: '', alphabet_audio: '', alphabet_image: '' },
  { japanese_character: 'ゆ', romaji_character: 'yu', alphabet_audio: 'D:/alphabet/hiragana/audio/yu', alphabet_image: 'D:/alphabet/hiragana/image/yu'},
  { japanese_character: '', romaji_character: '', alphabet_audio: '', alphabet_image: '' },
  { japanese_character: 'よ', romaji_character: 'yo', alphabet_audio: 'D:/alphabet/hiragana/audio/yo', alphabet_image: 'D:/alphabet/hiragana/image/yo'},
  { japanese_character: 'ら', romaji_character: 'ra', alphabet_audio: 'D:/alphabet/hiragana/audio/ra', alphabet_image: 'D:/alphabet/hiragana/image/ra'},
  { japanese_character: 'り', romaji_character: 'ri', alphabet_audio: 'D:/alphabet/hiragana/audio/ri', alphabet_image: 'D:/alphabet/hiragana/image/ri'},
  { japanese_character: 'る', romaji_character: 'ru', alphabet_audio: 'D:/alphabet/hiragana/audio/ru', alphabet_image: 'D:/alphabet/hiragana/image/ru'},
  { japanese_character: 'れ', romaji_character: 're', alphabet_audio: 'D:/alphabet/hiragana/audio/re', alphabet_image: 'D:/alphabet/hiragana/image/re'},
  { japanese_character: 'ろ', romaji_character: 'ro', alphabet_audio: 'D:/alphabet/hiragana/audio/ro', alphabet_image: 'D:/alphabet/hiragana/image/ro'},
  { japanese_character: 'わ', romaji_character: 'wa', alphabet_audio: 'D:/alphabet/hiragana/audio/wa', alphabet_image: 'D:/alphabet/hiragana/image/wa'},
  { japanese_character: '', romaji_character: '', alphabet_audio: '', alphabet_image: '' },
  { japanese_character: 'を', romaji_character: 'wo', alphabet_audio: 'D:/alphabet/hiragana/audio/wo', alphabet_image: 'D:/alphabet/hiragana/image/wo'},
  { japanese_character: '', romaji_character: '', alphabet_audio: '', alphabet_image: '' },
  { japanese_character: 'ん', romaji_character:'n', alphabet_audio: 'D:/alphabet/hiragana/audio/n', alphabet_image: 'D:/alphabet/hiragana/image/n'}
]
